version: "3"

services:
  webserver-fixed:
    build: 
      context: ./bin/${PHPVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-${COMPOSE_PROJECT_VERSION}-${PHPVERSION}'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - database-fixed
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - fixed-network
  database-fixed:
    build:
      context: "./bin/${DATABASE}"
    container_name: '${COMPOSE_PROJECT_NAME}-${COMPOSE_PROJECT_VERSION}-${DATABASE}'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ${MYSQL_SCRIPTS_DIR-./config/mysql/scripts}:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - fixed-network
  # phpmyadmin-fixed:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: '${COMPOSE_PROJECT_NAME}-${COMPOSE_PROJECT_VERSION}-phpmyadmin'
  #   links:
  #     - database-fixed
  #   environment:
  #     PMA_HOST: database-fixed
  #     PMA_PORT: 3306
  #     PMA_USER: root
  #     PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     UPLOAD_LIMIT: ${UPLOAD_LIMIT}
  #     MEMORY_LIMIT: ${MEMORY_LIMIT}
  #   ports:
  #     - '${HOST_MACHINE_PMA_PORT}:80'
  #   volumes: 
  #     - /sessions
  #     - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  #   networks:
  #     - fixed-network

networks:
  fixed-network:
    # driver_opts:
    #   com.docker.network.bridge.host_binding_ipv4: "172.21.0.1"
    # ipam:
    #   config:
    #     - subnet: "172.21.0.0/16"